<?php

function challenge_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
	// selects which forms are going to call validate hook
	// when creating a company type and when editing company type
	if (($form_id === 'node_company_form') || ($form_id === 'node_company_edit_form') ) {
		$form['#validate'][] = 'challenge_node_company_form_validate';
	}

}


function challenge_node_company_form_validate(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {

	// gets value from field_email
	$email = $form_state->getValue('field_email');
	$email_value = $email[0]['value'];

	// checks if begining of value from email field is the same as no-reply
	preg_match("/no-reply/", $email_value, $value);
	if($value[0] === "no-reply") {
		$form_state->setErrorByName('field_email', t('Please enter a valid response email'));
	}
	
}

